import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { chromium } from '@playwright/test';
import ffmpeg from 'ffmpeg-static';

const basit='data:image/jpeg;base64,'+fs.readFileSync('submission/abdul-basit.jpeg').toString('base64');
const muizz='data:image/jpeg;base64,'+fs.readFileSync('submission/abdul-muizz.jpeg').toString('base64');
const person=(name,role,src)=>`<article class="person"><img src="${src}" alt="${name}"/><div><h2>${name}</h2><p>${role}</p></div></article>`;
const portraits=person('Abdul Basit','Product & UI',basit)+person('Abdul Muizz','Model & Evaluation',muizz);
const style=`*{box-sizing:border-box}body{margin:0;background:#faf6ed;color:#244634;font:24px Arial,sans-serif}.layout{padding:32px 56px}header{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #d9dece;padding-bottom:16px}.brand{font:700 35px Georgia}.meta{font-size:15px;letter-spacing:2px;color:#6a7a61}h1{font:48px Georgia;margin:23px 0 12px}.intro{font-size:20px;color:#6a795f;margin:0 0 24px}.people{display:grid;grid-template-columns:1fr 1fr;gap:28px}.person{background:#fffdf8;border:1px solid #d5decb;border-radius:16px;overflow:hidden;margin:0}.person img{display:block;width:100%;height:382px;object-fit:cover;object-position:center 47%}.person>div{padding:17px 23px}.person h2{font:25px Georgia;margin:0 0 5px}.person p{font-size:17px;color:#63775a;margin:0}.bottom{display:flex;justify-content:space-between;font-size:14px;color:#75856c;margin-top:20px}.focus .people{grid-template-columns:430px 1fr}.focus .person img{height:365px}.message{background:#eaf0df;border:1px solid #d3dfc6;border-radius:16px;padding:38px;display:flex;flex-direction:column;justify-content:center}.message h2{font:36px Georgia;margin:0 0 22px}.message p{font-size:23px;line-height:1.6;margin:0 0 16px}.pill{font-size:15px;background:#174d38;color:#faf6ed;padding:12px 17px;border-radius:8px;align-self:start}.closing .people{grid-template-columns:360px 360px;justify-content:center}.closing .person img{height:285px}.closing h1{text-align:center;margin-top:30px}.closing .intro{text-align:center}.closing .bottom{justify-content:center;gap:30px}.photo .layout{padding:40px 65px}.photo h1{font-size:66px}.photo .person img{height:620px}.photo .person h2{font-size:32px}.photo .person p{font-size:22px}.photo .intro{font-size:25px}.photo .bottom{font-size:18px}`;
const html=(content,kind='')=>`<!doctype html><html><head><meta charset="utf-8"><style>${style}</style></head><body class="${kind}"><div class="layout"><header><span class="brand">pakka.</span><span class="meta">TEAM 2AM · PAKISTAN</span></header>${content}</div></body></html>`;
const footer='<div class="bottom"><span>Original supplied photographs · Portrait collage</span><span>Team 2AM · Pakka</span></div>';
const frames=[
 {duration:12,html:html(`<h1>Meet Team 2AM.</h1><p class="intro">Two people. One practical promise.</p><div class="people">${portraits}</div>${footer}`)},
 {duration:9,html:html(`<h1>Abdul Basit.</h1><p class="intro">Product & UI</p><div class="people">${person('Abdul Basit','Product & UI',basit)}<section class="message"><h2>Clear, usable, local.</h2><p>A mobile-first interface for small farm hosts.</p><p>Editable offerings. Operator review. English and Urdu receipts.</p><span class="pill">The host stays in control</span></section></div>${footer}`,'focus')},
 {duration:9,html:html(`<h1>Abdul Muizz.</h1><p class="intro">Model & Evaluation</p><div class="people">${person('Abdul Muizz','Model & Evaluation',muizz)}<section class="message"><h2>Small model. Honest results.</h2><p>Local topic detection, transparent comparisons, and reproducible checks.</p><p>Uncertain requests stay open for clarification.</p><span class="pill">Measure and report limitations</span></section></div>${footer}`,'focus')},
 {duration:18,html:html(`<h1>A clear promise before the visit.</h1><p class="intro">Offline tourism request checking for Pakistan’s small farm hosts.</p><div class="people">${portraits}</div><div class="bottom"><span>English guest requests</span><span>English + Urdu receipts</span><span>Guest agreement pending</span></div>`,'closing')}
];
fs.mkdirSync('.cache/team-frames',{recursive:true});
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1280,height:720}});
let concat='';for(let i=0;i<frames.length;i++){await page.setContent(frames[i].html);await page.locator('img').first().waitFor();await page.evaluate(()=>Promise.all([...document.images].map(img=>img.decode())));const file=path.resolve(`.cache/team-frames/${i}.png`).replaceAll('\\','/');await page.screenshot({path:file});concat+=`file '${file}'\nduration ${frames[i].duration}\n`;}
concat+=`file '${path.resolve('.cache/team-frames/3.png').replaceAll('\\','/')}'\n`;fs.writeFileSync('.cache/team-frames/concat.txt',concat);
await page.setViewportSize({width:1600,height:1000});
await page.setContent(html(`<h1>Team 2AM.</h1><p class="intro">Pakka · A clear promise before the visit.</p><div class="people">${portraits}</div>${footer}`,'photo'));
await page.evaluate(()=>Promise.all([...document.images].map(img=>img.decode())));
await page.screenshot({path:'submission/team-photo.png',fullPage:true});
await browser.close();
const output='submission/team-introduction.mp4';const r=spawnSync(ffmpeg,['-y','-f','concat','-safe','0','-i','.cache/team-frames/concat.txt','-i','submission/team-narration.mp3','-filter_complex','[1:a]apad[a]','-map','0:v','-map','[a]','-t','48','-r','25','-c:v','libx264','-preset','medium','-crf','20','-pix_fmt','yuv420p','-c:a','aac','-b:a','128k','-movflags','+faststart',output],{encoding:'utf8'});if(r.status!==0)throw Error(r.stderr);
const p=spawnSync(ffmpeg,['-i',output,'-f','null','-'],{encoding:'utf8'});const d=p.stderr.match(/Duration: (\d+):(\d+):(\d+\.\d+)/);if(!d)throw Error('Missing duration');const seconds=Number(d[1])*3600+Number(d[2])*60+Number(d[3]);if(seconds>60)throw Error('Too long');fs.writeFileSync('submission/team-metadata.json',JSON.stringify({durationSeconds:seconds,bytes:fs.statSync(output).size,members:[{name:'Abdul Basit',role:'Product & UI'},{name:'Abdul Muizz',role:'Model & Evaluation'}],portraits:'Original user-supplied photos, no generated face or voice impersonation',narration:'ElevenLabs premade Bella voice'},null,2)+'\n');console.log(`Team introduction: ${seconds}s.`);

